---
version: '2'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=postgres
    volumes:
      - ./metabase/pg:/var/lib/postgresql/data
    networks: 
      - metabase_network
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
     - 3000:3000
    volumes:
      - /home/app/metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    networks: 
      - metabase_network
    links:
      - postgres:postgres

networks:
  metabase_network: