# Connection details
url=jdbc:snowflake://PFHRTLO-ARB20198.snowflakecomputing.com/?warehouse=compute_wh&db=dev&schema=public
driver=net.snowflake.client.jdbc.SnowflakeDriver

# Change log file
changeLogFile=db_changelog.xml
liquibase.hub.mode=off
