[tool.poetry]
name = "jyablonski-praq"
version = "2.8.12"
description = "Practice Repo"
authors = ["jyablonski9 <jyablonski9@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11,<3.12" # needed for snowpark package?  fk off dude
pandas = "2.0.3"
gspread = "^5.11.2"
boto3 = "^1.28.57"
jyablonski-common-modules = "^0.0.3"
thefuzz = "^0.20.0"
better-profanity = "^0.7.0"
lxml = "^4.9.3"
pyarrow = "^13.0.0"
aiohttp = "^3.8.6"
nba-api = "^1.3.1"
polars = "^1.2.0"
s3fs = "^2023.10.0"
mypy = "^1.6.1"
opensearch-logger = "^1.2.3"
faker = "^20.0.3"
awswrangler = "^3.4.2"
memory-profiler = "^0.61.0"
bs4 = "^0.0.1"
nltk = "^3.8.1"
praw = "^7.7.1"
sentry-sdk = "^1.38.0"
tweepy = "^4.14.0"
jsonpath-ng = "^1.6.0"
duckdb = "^0.9.2"
matplotlib = "^3.8.2"
connectorx = "^0.3.2"
pyiceberg = {extras = ["glue"], version = "^0.6.1"}
redis = "^5.0.3"
rapidfuzz = "^3.6.2"
pytest = "^8.1.1"
pip = "^24.0"
mysql-connector-python = "^8.4.0"
alt-profanity-check = "^1.5.0"
gensim = "^4.3.2"
scipy = "1.12.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"
ruff = "^0.4.4"
moto = {extras = ["all"], version = "^5.0.9"}
pytest-mock = "^3.14.0"
snowflake-snowpark-python = {extras = ["localtest"], version = "^1.18.0"}
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"