# Connection details
url=jdbc:snowflake://HDNYJCW-JJB19248.snowflakecomputing.com/?db=development&schema=public
driver=net.snowflake.client.jdbc.SnowflakeDriver

# Change log file
changeLogFile=db_changelog.xml
liquibase.hub.mode=off
