# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.


# this solution trivializes the "shuffle"
# basically each character has an ASCII numeric representation
# so just sum `s` and `t` for those numeric representations and then
# get the numeric difference, then run `chr(res)` on that to get the char
def solution(s: str, t: str) -> str:
    sum_s = sum(map(ord, s))
    sum_t = sum(map(ord, t))

    # subtract t from s because t has the extra char
    res = sum_t - sum_s
    return chr(res)


s1 = "abcd"
t1 = "abcde"

s2 = ""
t2 = "y"

s3 = "abc"
t3 = "abca"

b = solution(s=s1, t=t1)
b = solution(s=s2, t=t2)
b = solution(s=s3, t=t3)


# old solution but wasnt supposed to work as the new character in t might be one of the characters in s
def solution(s: str, t: str) -> str:
    for char in t:
        if char not in s:
            return char
