services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: retl_benchmark
      POSTGRES_USER: bench
      POSTGRES_PASSWORD: bench
    ports:
      - "5499:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: "1g"
    command:
      - "postgres"
      - "-c" 
      - "shared_buffers=512MB"
      - "-c"
      - "work_mem=256MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "max_wal_size=2GB"
      - "-c"
      - "checkpoint_completion_target=0.9"

volumes:
  pgdata:
