name: Lint & Bump bby
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # https://github.com/wearerequired/lint-action
  push:
    branches:
      - jacob
  pull_request:
    branches:
      - jacob

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          auto_fix: true

  build:
    runs-on: ubuntu-latest
    needs: run-linters
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: jaumann/github-bumpversion-action@v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
