name: Sync Manifest
on:
  pull_request:
    types:
      - closed

jobs:
  build-push-site:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'sync-manifest') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Sync
        run: |
          echo "PR was merged with 'sync-manifest' label. Proceeding..."
          echo "Running sync job..."
          echo "beep boop beep boop"
          echo "Sync job completed successfully."
